[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "OpenSSL"
]

[[bans.deny]]
name = "serde_derive"
version = ">1.0.171, < 1.0.184"
