[tool.poetry]
name = "tool.poetry"
version = "0.1.0"
description = "Firecracker python dependencies"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
aws-embedded-metrics = "^3.1.0"
black = "^24.3.0"
# Gitlint locks this to 8.1.3. Lock from our side too to prevent different versions
click = "8.1.3"
gitlint = "^0.19.1"
ipython = "^8.15.0"
isort = "^5.12.0"
mdformat = "^0.7.17"
mdformat-gfm = "^0.3.5"
mdformat-footnote = "^0.1.1"
mdformat-frontmatter = "^2.0.8"
openapi-spec-validator = "^0.5.6"
pandas = "^2.0.1"
psutil = "^5.9.5"
pylint = "^2.17.4"
pytest = "^7.3.1"
pytest-json-report = "^1.5.0"
pytest-rerunfailures = "^11.1.2"
pytest-timeout = "^2.1.0"
pytest-xdist = "^3.3.1"
python = "3.10.*"
PyYAML = "^6.0"
# Pin requests because of https://github.com/msabramo/requests-unixsocket/issues/73
requests = "<2.32.0"
requests-unixsocket = "^0.3.0"
scipy = "^1.11.2"
setproctitle = "^1.3.2"
tenacity = "^8.2.2"
# Fix urllib3 to a version <2.0.0 because requests breaks otherwise
# See https://github.com/psf/requests/issues/6432
urllib3 = "1.26.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
