[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
anyhow = "1.0.93"
acpi_tables = { path = "../acpi-tables" } 
aes-gcm =  { version = "0.10.1", default-features = false, features = ["aes"] }
aws-lc-rs = { version = "1.11.0", features = ["bindgen"] }
base64 = "0.22.1"
bincode = "1.2.1"
bitflags = "2.6.0"
crc64 = "2.0.0"
derive_more = { version = "1.0.0", default-features = false, features = ["from", "display"] }
displaydoc = "0.2.5"
event-manager = "0.4.0"
hex = "0.4.3"
kvm-bindings = { version = "0.8.1", features = ["fam-wrappers", "serde"] }
kvm-ioctls = "0.17.0"
lazy_static = "1.5.0"
libc = "0.2.164"
linux-loader = "0.11.0"
log = { version = "0.4.22", features = ["std", "serde"] }
log-instrument = { path = "../log-instrument", optional = true }
memfd = "0.6.3"
micro_http = { git = "https://github.com/firecracker-microvm/micro-http" }

seccompiler = { path = "../seccompiler" }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive", "rc"] }
serde_json = "1.0.133"
slab = "0.4.7"
smallvec = "1.11.2"
thiserror = "2.0.3"
timerfd = "1.5.0"
userfaultfd = "0.8.1"
utils = { path = "../utils" }
vhost = { version = "0.13.0", features = ["vhost-user-frontend"] }
vm-allocator = "0.1.0"
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-bitmap"] }
vm-superio = "0.8.0"
zerocopy = { version = "0.8.10" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
vm-fdt = "0.3.0"

[dev-dependencies]
criterion = { version = "0.5.0", default-features = false }
device_tree = "1.1.0"
itertools = "0.13.0"
proptest = { version = "1.5.0", default-features = false, features = ["std"] }

[features]
tracing = ["log-instrument"]

[[bench]]
name = "cpu_templates"
harness = false

[[bench]]
name = "queue"
harness = false

[[bench]]
name = "block_request"
harness = false

[lints]
workspace = true
