[build]
target-dir = "build/cargo_target"
rustflags = [
  "-Ccodegen-units=1",
]

[net]
git-fetch-with-cli = true

[source.crates-io]
replace-with = 'ustc'
[source.ustc]
registry = "http://mirrors.ustc.edu.cn/crates.io-index"