[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
derive_more = { version = "1.0.0", default-features = false, features = ["from"] }
displaydoc = "0.2.5"
libc = "0.2.161"
log-instrument = { path = "../log-instrument", optional = true }
serde = { version = "1.0.213", features = ["derive"] }
thiserror = "1.0.65"
vm-memory = { version = "0.16.0", features = ["backend-mmap", "backend-bitmap"] }
vmm-sys-util = { version = "0.12.1", features = ["with-serde"] }

[dev-dependencies]
serde_json = "1.0.132"

[features]
tracing = ["log-instrument"]

[lints]
workspace = true
